// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluERw8qeeI0dbaw6JA33NQBUHDVL7lmg',
    appId: '1:382852329743:web:14563ec87def1d91c38e7a',
    messagingSenderId: '382852329743',
    projectId: 'shop-96036',
    authDomain: 'shop-96036.firebaseapp.com',
    storageBucket: 'shop-96036.firebasestorage.app',
    measurementId: 'G-JELQ9W6ZDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbOt_UuzIO1halwTsj9b2NoXi4KVkA2ho',
    appId: '1:382852329743:android:6de8de1be04ee7e8c38e7a',
    messagingSenderId: '382852329743',
    projectId: 'shop-96036',
    storageBucket: 'shop-96036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6JmhzMohmO-PC2KFyfRha8E4LnB3LRBc',
    appId: '1:382852329743:ios:9c0425f62ec44201c38e7a',
    messagingSenderId: '382852329743',
    projectId: 'shop-96036',
    storageBucket: 'shop-96036.firebasestorage.app',
    iosClientId: '382852329743-0q2pu9v1tcs8g0phn01nkd8heeffm6pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6JmhzMohmO-PC2KFyfRha8E4LnB3LRBc',
    appId: '1:382852329743:ios:9c0425f62ec44201c38e7a',
    messagingSenderId: '382852329743',
    projectId: 'shop-96036',
    storageBucket: 'shop-96036.firebasestorage.app',
    iosClientId: '382852329743-0q2pu9v1tcs8g0phn01nkd8heeffm6pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAluERw8qeeI0dbaw6JA33NQBUHDVL7lmg',
    appId: '1:382852329743:web:79c314bbb4c94499c38e7a',
    messagingSenderId: '382852329743',
    projectId: 'shop-96036',
    authDomain: 'shop-96036.firebaseapp.com',
    storageBucket: 'shop-96036.firebasestorage.app',
    measurementId: 'G-1LGPEMKZMR',
  );
}
